### ISSUE TITLE
Deprecate this repository 

### ISSUE THREAD

**Issue by CK-Ward** [ngrok/ngrok-api-scala#10]
Request for:

- [ ] this repository to be prefixed with `[DEPRECATED]`
- [ ] archive the repository 

Reference: https://apache.googlesource.com/cordova-contribute/+/HEAD/deprecation.md#deprecation-notice

cc @nijikokun

**Comment by krwenholz** [comment]
Noting: our API logs show zero usage of this client library for at least the past 15 days.
